tap "caskroom/cask"
# upgrade casks
tap "buo/cask-upgrade"
# completions
tap "homebrew/completions"

brew "ansible"
brew "asciinema"
brew "awscli"
brew "bash-completion"
brew "bash-git-prompt"
brew "brew-cask-completion"
brew "cloc"
brew "gist"
brew "git"
brew "git-flow"
brew "go"
brew "h2"
brew "htop"
brew "httpie"
brew "httrack"
brew "hub"
brew "ipfs"
brew "jq"
brew "kubectl"
brew "links"
brew "lynx"
brew "mackup"
brew "mas"
# brew "maven-completion"
brew "nmap"
brew "node"
brew "putty"
brew "pyenv"
brew "rbenv"
brew "ssh-copy-id"
brew "terraform"
brew "tor"
brew "trash"
brew "tree"
brew "vault"
brew "vcprompt"
brew "youtube-dl"
brew "watch"
brew "wget"

# Cask apps
cask "adobe-acrobat-reader"
cask "alfred"
cask "android-file-transfer"
# KO - requires java
#cask "android-sdk"
cask "atom"
cask "box-sync"
cask "charles"
# cask "dbeaver-community"
cask "dbvisualizer"
cask "docker"
brew "docker-completion"
cask "dropbox"
cask "dupeguru"
cask "dbeaver-community"
cask "enpass"
cask "firefox"
cask "flux"
cask "gimp"
cask "gpgtools"
cask "google-backup-and-sync"
cask "google-chrome"
cask "google-hangouts"
cask "xquartz"
# requires install xquartz
cask "inkscape"
cask "intellij-idea"
cask "iterm2"
cask "jd-gui"
cask "jdownloader"
cask "kitematic"
cask "lastpass"
cask "libreoffice"
cask "minikube"
cask "postman"
cask "qbittorrent"
cask "skype"
cask "slack"
cask "soapui"
cask "spectacle"
cask "spotify"
cask "sublime-text"
cask "telegram"
cask "the-unarchiver"
cask "tunnelblick"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "xmind"
cask "wireshark"

# Mac App Store
mas "Be Focused", id: 973134470
# Unavailable
# mas "Gapplin", id: 768053424
mas "Giphy Capture", id: 668208984
# Unavailable
# mas "GIFs", id: 662754936
mas "IP Scanner", id: 404167149
mas "Irvue", id: 1039633667
#mas "SnappyApp", id: 512617038
mas "TweetDeck", id: 485812721
mas "Twitter", id: 409789998
mas "Wallble", id: 549018561
